language: node_js
node_js: '10'
sudo: required
services:
  - docker
after_success:
  - bin/docker_push.sh
script: yarn build
addons:
  apt:
    packages:
      - docker-ce
notifications:
  email: false
